package com.benjamin.su.decompiler;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.Status;
import org.eclipse.jdt.core.IClassFile;
import org.eclipse.jdt.ls.core.internal.JDTUtils;
import org.eclipse.jdt.ls.core.internal.preferences.Preferences;
import org.jetbrains.java.decompiler.main.decompiler.BaseDecompiler;
import org.jetbrains.java.decompiler.main.extern.IFernflowerLogger;
import org.jetbrains.java.decompiler.main.extern.IResultSaver;

import java.io.File;
import java.io.InputStream;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.jar.Manifest;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

public class VineflowerDecompiler extends CachingDecompiler {

    public static final String DECOMPILED_HEADER =
            " // Source code is unavailable, and was generated by the Vineflower decompiler.\n";

    private static final IFernflowerLogger SILENT_LOGGER = new IFernflowerLogger() {
        @Override public void writeMessage(String message, Severity severity) {}
        @Override public void writeMessage(String message, Severity severity, Throwable t) {}
    };

    @Override
    public void setPreferences(Preferences preferences) {
        // TODO: map java.decompiler.procyon settings to Vineflower options if needed
    }

    private URI normalizeUri(URI uri) {
        String path = uri.getPath();
        if (path != null && path.matches("/[A-Za-z]:/.*")) {
            char drive = Character.toLowerCase(path.charAt(1));
            String rest = path.substring(3).replace('\\', '/');
            try {
                return new URI("file", null, "/mnt/" + drive + "/" + rest, null);
            } catch (Exception e) {
                return uri;
            }
        }
        return uri;
    }

    private Map<String, Object> buildOptions() {
        Map<String, Object> opts = new HashMap<>();
        opts.put("bytecode-source-mapping", "1");
        opts.put("__dump_original_lines__", "1");
        opts.put("force-explicit-imports", "1");
        return opts;
    }

    @Override
    protected String decompileContent(URI uri, IProgressMonitor monitor) throws CoreException {
        uri = normalizeUri(uri);
        IClassFile classFile = JDTUtils.resolveClassFile(uri);
        if (classFile != null) return decompileContent(classFile, monitor);
        try {
            File f = new File(uri.getPath());
            if (f.exists()) return runDecompiler(f, null);
        } catch (Exception e) {
            throw new CoreException(new Status(4, "com.benjamin.su.decompiler", "Error decompiling", e));
        }
        return null;
    }

    @Override
    protected String decompileContent(IClassFile classFile, IProgressMonitor monitor) throws CoreException {
        try {
            byte[] bytes = classFile.getBytes();
            Path tmp = Files.createTempFile("vf-", ".class");
            try {
                Files.write(tmp, bytes);
                return runDecompiler(tmp.toFile(), null);
            } finally {
                Files.deleteIfExists(tmp);
            }
        } catch (Exception e) {
            throw new CoreException(new Status(4, "com.benjamin.su.decompiler", "Error decompiling", e));
        }
    }

    String decompileFromJar(String archivePath, String internalName, IProgressMonitor monitor) throws Exception {
        try (ZipFile zf = new ZipFile(archivePath)) {
            return decompileFromZip(zf, internalName, new File(archivePath));
        }
    }

    String decompileFromNestedJar(String archivePath, String nestedEntry, String internalName, IProgressMonitor monitor) throws Exception {
        try (ZipFile outer = new ZipFile(archivePath)) {
            ZipEntry nested = outer.getEntry(nestedEntry);
            if (nested == null) return null;
            Path tmp = Files.createTempFile("vf-nested-", ".jar");
            try {
                try (InputStream is = outer.getInputStream(nested)) {
                    Files.write(tmp, is.readAllBytes());
                }
                try (ZipFile inner = new ZipFile(tmp.toFile())) {
                    return decompileFromZip(inner, internalName, tmp.toFile());
                }
            } finally {
                Files.deleteIfExists(tmp);
            }
        }
    }

    private String decompileFromZip(ZipFile zf, String internalName, File libraryJar) throws Exception {
        String prefix = resolvePrefix(zf, internalName);
        if (prefix == null) return null;

        // collect outer class + all inner classes (Foo$Bar, Foo$1, etc.)
        String outerKey = prefix + internalName + ".class";
        String innerPrefix = prefix + internalName + "$";
        List<Map.Entry<String, byte[]>> sources = new ArrayList<>();
        Enumeration<? extends ZipEntry> entries = zf.entries();
        while (entries.hasMoreElements()) {
            ZipEntry e = entries.nextElement();
            String name = e.getName();
            if (name.equals(outerKey) || name.startsWith(innerPrefix)) {
                try (InputStream is = zf.getInputStream(e)) {
                    byte[] bytes = is.readAllBytes();
                    sources.add(Map.entry(name, bytes));
                }
            }
        }
        if (sources.isEmpty()) return null;
        return runDecompilerWithSources(sources, internalName, libraryJar);
    }

    private String resolvePrefix(ZipFile zf, String internalName) {
        for (String prefix : new String[]{"", "WEB-INF/classes/", "BOOT-INF/classes/"}) {
            if (zf.getEntry(prefix + internalName + ".class") != null) return prefix;
        }
        return null;
    }

    private String runDecompilerWithSources(List<Map.Entry<String, byte[]>> sources, String internalName, File libraryJar) throws Exception {
        List<Path> tmpFiles = new ArrayList<>();
        try {
            String[] result = {null};
            IResultSaver saver = new IResultSaver() {
                @Override public void saveFolder(String path) {}
                @Override public void copyFile(String source, String path, String entry) {}
                @Override public void saveClassFile(String path, String qualifiedName, String entryName, String content, int[] mapping) {
                    // capture only the outer class (not inner classes which end with $...)
                    if (!entryName.contains("$")) result[0] = content;
                    else if (result[0] == null) result[0] = content; // fallback if outer wasn't captured
                }
                @Override public void createArchive(String path, String name, Manifest mf) {}
                @Override public void saveDirEntry(String path, String name, String entry) {}
                @Override public void copyEntry(String src, String path, String name, String entry) {}
                @Override public void saveClassEntry(String path, String name, String q, String entry, String content) {}
                @Override public void closeArchive(String path, String name) {}
            };

            BaseDecompiler decompiler = new BaseDecompiler(saver, buildOptions(), SILENT_LOGGER);
            if (libraryJar != null) decompiler.addLibrary(libraryJar);

            for (Map.Entry<String, byte[]> src : sources) {
                Path tmp = Files.createTempFile("vf-", ".class");
                tmpFiles.add(tmp);
                Files.write(tmp, src.getValue());
                decompiler.addSource(tmp.toFile());
            }

            try {
                decompiler.decompileContext();
            } catch (Exception e) {
                if (result[0] == null) return null;
            }

            if (result[0] == null) return null;
            try {
                return new LineNumberFormatter(result[0]).reformatFile() + "\n" + DECOMPILED_HEADER;
            } catch (Exception e) {
                return result[0] + "\n" + DECOMPILED_HEADER;
            }
        } finally {
            for (Path tmp : tmpFiles) Files.deleteIfExists(tmp);
        }
    }

    private String runDecompiler(File classFile, File libraryJar) throws Exception {
        String[] result = {null};

        IResultSaver saver = new IResultSaver() {
            @Override public void saveFolder(String path) {}
            @Override public void copyFile(String source, String path, String entry) {}
            @Override public void saveClassFile(String path, String qualifiedName, String entryName, String content, int[] mapping) {
                result[0] = content;
            }
            @Override public void createArchive(String path, String name, Manifest mf) {}
            @Override public void saveDirEntry(String path, String name, String entry) {}
            @Override public void copyEntry(String src, String path, String name, String entry) {}
            @Override public void saveClassEntry(String path, String name, String q, String entry, String content) {}
            @Override public void closeArchive(String path, String name) {}
        };

        BaseDecompiler decompiler = new BaseDecompiler(saver, buildOptions(), SILENT_LOGGER);
        if (libraryJar != null) decompiler.addLibrary(libraryJar);
        decompiler.addSource(classFile);
        decompiler.decompileContext();

        if (result[0] == null) return null;

        try {
            return new LineNumberFormatter(result[0]).reformatFile() + "\n" + DECOMPILED_HEADER;
        } catch (Exception e) {
            return result[0] + "\n" + DECOMPILED_HEADER;
        }
    }
}
